config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  root 'welcome#index'

  resources :outings do
  	member do
  		resources :activities, only: [:index]
  	end 
  end 

  resources :activities, except: [:index] 

  resources :users, only: [:show]

  post '/new_email' => 'users#new_email'

end

app/models/Activity.rb
class Activity < ActiveRecord::Base 
	has_and_belongs_to_many :outings
end

app/models/activity.rb
class Activity < ActiveRecord::Base 
	has_and_belongs_to_many :outings
end

app/models/outing.rb
class Outing < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :activities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :outings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	before_action :authenticate_user!, except: [:show, :index]

	def create
		@outing = Outing.last
		@activity = @outing.activities.create(activity_params)
		if @activity.save
			respond_to do |format|
				format.html { redirect_to outings_path }
				format.json { render json: @outing }
			end 
		else 
			respond_to do |format|
				format.html { render :new }
				format.json { render status: 404 }
			end 
		end
	end

	def index
		@outing = Outing.find(params[:id])
		@activities = @outing.activities

		respond_to do |format|
			format.html 
			format.json { render json: @activities }
		end 
	end

	def show
		@activity = Activity.find(params[:id])
		respond_to do |format|
			format.html
			format.json { render json: @activity }
		end 
	end

	def destroy
		@outing = Collection.find(params[:outing_id])
		@activity = @outing.activities.find(params[:id])
		@activity.destroy
		redirect_to outing_path(@outing)
	end

	private

	def activity_params
		params.require(:activity).permit(:name, :category, :event_id, :event_url, :longitude, :latitude) 
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/outings_controller.rb
class OutingsController < ApplicationController

	# before_action :authenticate_user!, except: [:show, :index]

	def index
	  @outings = Outing.all

	  respond_to do |format|
	  	format.html
	  	format.json { render json: @outings }
	  end 
	end

	def new
	  @outing = Outing.new
	end

	def show
	  @outing = Outing.find(params[:id])
	  @activities = @outing.activities

	  respond_to do |format|
	  	format.html
	  	format.json { render json: @outing }
	  end 
	end

	def edit
	  @outing = Outing.find(params[:id])
	end

	def create
	  @outing = Outing.new(outing_params)#.merge(user_id: current_user.id))
	  if @outing.save
	    respond_to do |format|
	    	format.html { redirect_to @outing }
	    	format.json { render json: @outing }
	    end 
	  else
	    respond_to do |format|
	    	format.html { redirect_to new_outing_path }
	    	format.json { render status: 404}
	    end 
	  end
	end

	def destroy
	  @outing = Outing.find(params[:id])
	  @outing.destroy
	  redirect_to outings_url
	end

	private

	def outing_params
	  params.require(:outing).permit(:name, :date, :city, :user_id)
	end	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
	  @user = User.find(params[:id])	
	  @outings = Outing.where(:user_id => @user.id)
	end

	def new_email
		@user = current_user
		@participants = params[:participants]
		@outing_link = params[:url]
		begin
			ParticipantMailer.send_email(@participants, @outing_link, @user).deliver
		end 
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
	before_action :authenticate_user!, except: [:index]

	def index
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/index.html.erb
<% @activities.each do |activity| %>
<%= activity.name %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
<html>
<head>
  <title>Mappetize</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
  <script src='https://api.tiles.mapbox.com/mapbox.js/v2.1.2/mapbox.js'></script>
	<link href='https://api.tiles.mapbox.com/mapbox.js/v2.1.2/mapbox.css' rel='stylesheet'/>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
</head>
<body>

    <title><%= content_for?(:title) ? yield(:title) : "Mappetizer" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
	<header>
		<div class="sticky">
    		<nav class="top-bar">
		        <ul class="title-area">
		          <li class="name">
		             <h1><a href="/"><span class="logo">&#8984; </span> <span class="logo-name">MAPPETIZE</a></span></h1>
		          </li>
		          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a>
		          </li>
		        </ul>
				<section class="top-bar-section">
		    	  <ul class="left">
		            <li class="divider"></li>
		            <!-- <li><a href="#">Main Item 1</a></li>
		            <li class="divider"></li>
		            <li><a href="#">Main Item 2</a></li>
		            <li class="divider"></li>
					<li class="has-dropdown"><a href="#">Main Item 3</a>
					    <ul class="dropdown">
					      <li><a href="#">Dropdown Level 3a</a></li>
					      <li><a href="#">Dropdown Level 3b</a></li>
					      <li><a href="#">Dropdown Level 3c</a></li>
					    </ul>
					</li> -->
					<!-- <li class="divider"></li> -->
		          </ul>
				  <ul class="right">
		            <li class="divider"></li>
		            <% if user_signed_in? %>
		              <li><a href="#"></a>
		              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
		            <% else %>
		              <li><a href="#"></a>
		              <%= link_to('Login', new_user_session_path)  %></li>
		              <li class="divider"></li>
		              <li><a href="#"></a>
		              <%= link_to('Register', new_user_registration_path) %></li>
		              <li class="divider"></li>
			        <% end %>
		          </ul>
		        </section>     	
		    </nav>
        </div>
	</header>
  
  <div class="wrapper">
    <%= yield %>
  </div> <!-- closes wrapper -->

    <div class="footer-area">
	    <ul>
	      <li>About Us</li>
	      <li>Blog</li>
	      <li>Press</li>
	      <li>Jobs</li>
	      <li>Privacy</li>
	      <li>Terms</li>
	      <li>&copy; 2014 Mappetizer</li>
	    </ul>
    </div>

  	<footer></footer>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/outings/index.html.erb
<div class="row container" data-id="<%= current_user.id %>">

	<div class="new_outing small-4 columns side_box" id="overwrite_foundation_toppad">	

		<form>
			<label> Select Outing Location </label>
			<input type="text" id="location" placeholder="City">
			<div class="row">
				<div class="small-7 columns">
					<label> Start date and time </label>
					<input type="date" id="start_date"> 
				</div>
				<div class="small-5 columns">
					<br>
					<input type="time" id="start_time">
				</div>
			</div>
			<div class="row">
				<div class="small-7 columns">
					<label> End date and time </label>
					<input type="date" id="end_date"> 
				</div>
				<div class="small-5 columns">
					<br>
					<input type="time" id="end_time">
				</div>
			</div>
			<div id="outing_name">
				<label> Name your Outing </label>
				<input type="text" placeholder="">
			</div>
			<div class="row"> 
				<div class="button small search"> Search</div>
			</div>
			<div class="row">
				<div class="button small save_location"></div>
			</div>
		</form>
	</div>

	<div class='small-4 columns'>
		<div class='row new_outing_info'>
		
		</div>
		
		<div class='row'>	
			<div class="new_activity_info columns">
				<!-- new activity goes here -->
			</div>
		</div>	

		<div class="row">
			<div class="button send-email"> Invite friends </div>
	 	</div>

	 	<div class="row email-form">
			<div class="emails-input">
				<input type="email" id="email1">
				<input type="email" id="email2">
				<input type="email" id="email3">
				<div class="small-6 columns">
					<div class="button" id="send-button"> Send </div>
				</div>
			</div>
</div>

	</div>


	<div class="small-8 columns" id="map">
		<!-- map goes here -->
	</div>

</div>

app/views/outings/show.html.erb
<div class="info row" data-id="<%= @outing.id %>" data-city="<%= @outing.city %>">
	
	<div class="small-4 columns">
	
		<div class='row'>

			<h2> <%= @outing.name  %>

			<small><%= @outing.date %></small></h2>

			<% @activities.each do |activity| %>

				<h4> Event: <%= activity.name %><h3>
					<p> Category: <%= activity.category %>
					</p>
					<h4> <%= link_to 'RSVP', activity.event_url %> </h4>
			<% end %>
		</div>

	</div>

	<div class="small-8 columns" id="map">
	</div>

</div>

app/views/users/show.html.erb
<!-- outings on the user page, we want anybody to be able to see it with the link sent over email -->

<%= @outings.each do |outing| %>
<div class="info">	
	<h2> <%= outing.name  %> 
		<small> <%= outing.date  %>
		</small> 
		<span> 
			<%= outing.city  %> 
		</span>
	</h2>

	<div>
		<%= link_to 'View', outing_path(outing)  %>
	</div>

	<div>
		<%= link_to 'Edit', edit_outing_path(outing) %>
	</div>

	<div>
		<%= link_to 'Delete', outing_path(outing), method: :delete %>		
	</div>
</div>
<% end %>

app/views/welcome/index.html.erb
<div class="row first">
  <div class="small-12 centered columns">
  <h1 class="icon">&#8984;</h1>
<h2 class="sub-logo">Mappetize your plans.</h2>
	   <% if !user_signed_in? %>
            <ul class="stack-for-medium round secondary button-group even-2">
			  <li class="button left-side">
			    <%= link_to "SIGN IN", new_user_session_path %></li>	
			  <li class="button right-side">
				<%= link_to "REGISTER", new_user_registration_path%></li>
		    </ul>
         </div>
	   <% else %>
		    <ul class="stack-for-medium round secondary button-group even-2">
			   <li class="button left-side">
		      		<%= link_to "SHOW MY OUTINGS", user_path(current_user)%></li>
			   <li class="button right-side">
					<%= link_to "CREATE AN OUTING", outings_path%></li>	
		  	</ul>
       <% end %>
  </div>
</div>